### ISSUE TITLE
What is the right way to show or hide 3D objects based on tracking/lost tracking of an ImageTarget? 

### ISSUE THREAD

**Issue by suhan0694** [viromedia/viro#776]
- [ ] Review the documentation: https://docs.viromedia.com/
  - [ ] Search for existing issues: https://github.com/viromedia/viro
  - [ ] Use the latest ViroReact release: https://docs.viromedia.com/docs/releases

## Environment
Please provide the following information about your environment:
1. Development OS: Windows
2. Device OS & Version: Android 10
3. Version: ViroReact version - 2.17.0 React Native version 0.59.9
4. Device(s): Pixel 3

## Description
We have multiple image targets in the scene and I am currently using a renderIf() dependent on the properties that I set in onAnchorFound. This works fine when I'm moving from ImageTarget1 to ImageTarget2. But when we move back to ImageTarget1 nothing happens. I figured out we must use onAnchorUpdated for this scenario. But using the anchor.trackingMethod with renderIf is causing the app to lag and sometimes it takes around 20 seconds to hide/show the 3D images.

Here is the code snippet of the methods
![image](https://user-images.githubusercontent.com/54325915/68990242-96c4bd00-0816-11ea-871b-e43563fc7eb7.png)
